- Makefile
- docker-compose.yml
- pre.yaml
- run-copy.yaml
- run.yaml
- zuul.yaml
Depends-On: https://github.com/wazo-pbx/sf-jobs/pull/4
> add a zuul job

- src/component/documentation/Layout.js
- src/component/documentation/index.js
- src/component/install/index.js
documentation: add breadcrumbs
make links relative
> Pull request for relative-links

- package.json
- run-copy.yaml
- run.yaml
- src/component/documentation/Layout.js
- src/component/documentation/index.js
- src/component/documentation/overview.js
- src/component/index.js
- src/component/install/index.js
zuul: build site with zuul build log prefix
zuul: use make module
Revert "Merge pull request #10 from wazo-pbx/relative-links"
> Pull request for gatsby-prefix

- content/blog/solving-the-emergency-call-priorization-issue-with-programmable-telecom.md
- src/component/Layout.js
- src/html.js
- src/styles/devaid.scss
- src/styles/main-styles.scss
- Fixes image urls in Jerome's latest post
- Fixes a problem with mobile menu
- Fixes dev-mode crash related to external JS
- Contribute: fix content padding
> Various fixes

- content/blog/new-public-release-wazo-1913.md
- content/sections.yaml
- src/component/documentation/index.js
documentation: add section anchors
blog: wazo-platform 19.13
> Pull request for wazo-platform-1913

- src/component/documentation/console.js
- src/styles/main-styles.scss
A couple of console-related fixes
> Fixes inadequately labeled loader + Refresh bug

- src/component/documentation/console.js
- Uses static data from openapi.wazo.community instead of overloading quintana
- Disable credential input and submit button when hostname is empty
Due credits: @fblackburn1
> WAZO-1243 Use openapi.wazo.community + disable token input when hostname is empty

- src/component/documentation/console.js
- Text inputs (server name and credentials) react to enter key;
- Removed dynamic disabling of button and API input (circumvents a bug);
> Add action on enter & fix

- content/blog/sprint-review-1915.md
- src/styles/main-styles.scss
blog: wazo platform 19.15 release
blog: remove bigger font
> Pull request for 19.15-review

- content/blog/sprint-review-1916.md
> blog: wazo platform 19.16 release

- content/confd/description.md
from: http://documentation.wazo.community/en/stable/api_sdk/rest_api/examples.html
> Add REST API example schema

- content/agentd/diagram.puml
- content/amid/diagram.puml
- content/blog/wazo-platform-c4-overview.md
- content/c4-router/description.md
- content/c4-router/diagram-c4.puml
- content/c4-sbc/description.md
- content/c4-sbc/diagram-c4.puml
- content/call-logd/diagram.puml
- content/calld/diagram.puml
- content/chatd/diagram.puml
- content/confd/diagram.puml
- content/dird/diagram.puml
- content/plugind/diagram.puml
- content/provd/diagram.puml
- content/router-confd/description.md
- content/router-confd/diagram-c4.puml
- content/rtpe-config/description.md
- content/rtpe-config/diagram-c4.puml
- content/webhookd/diagram.puml
- content/websocketd/diagram.puml
@mwolff44 please review the changes, based on your (late) review of pull/106
> Enh: class4 documentation (see: wazo-platform.org/pull/106)

- src/component/documentation/api.js
> Move API Resource URL to middle panel

- content/blog/wazo-c4-ansible.md
This PR adds a blog post on how to install C4 with ansible.
> Add: c4 ansible guide blog post

- .gitignore
- gatsby-node.js
- package.json
- yarn.lock
I tried at first to use the [Official Gatsby Plugin](https://www.gatsbyjs.org/packages/gatsby-plugin-feed/), but was causing too many errors and was not able to make it work with our website structure. So I decide to use a «manual» approach to generate the RSS Feed.
> Add RSS Feed

- content/blog/sprint-review-2004.md
- content/uc-doc/upgrade/upgrade_notes.md
blog: add 20.04 sprint review
doc: upgrade notes 20.04
> Pull request for release-20.04

- content/uc-doc/contributors/network.md
- content/uc-doc/upgrade/upgrade_notes.md
update default amid listen address/protocol
fix network table
upgrade note: deprecate TLS configuration for amid
upgrade note: move http configuration section
Depends-on: https://github.com/wazo-platform/wazo-platform.org/pull/149
> Pull request for WAZO-1682-amid-http

- content/uc-doc/contributors/contributing_to_wazo.md
- content/uc-doc/index.md
- content/uc-doc/introduction.md
- content/uc-doc/upgrade/migrate_i386_to_amd64.md
- content/uc-doc/upgrade/upgrade_notes_details/16-16/xivo_to_wazo.md
- src/component/uc-doc/TableOfContents.js
- src/styles/platform/styles.scss
uc-doc: fix css class name
uc-doc: fix links to install procedure
uc-doc: use internal links where possible
> Pull request for WAZO-1687-uc-doc-internal-links

- src/component/LayoutDev.js
- src/styles/dev/styles.scss
> Tweak developer site header to match corp site

- content/uc-doc/upgrade/upgrade_notes.md
transport wss is not transport-wss by default but could be named anything else
> add an upgrade note for the transport name changes

- content/contribute.md
- src/component/contribute/index.js
This text has been taken from the bigbluebutton project FAQ here: https://docs.bigbluebutton.org/support/faq.html#how-can-i-donate-money-to-the-project
> Add donate question

- content/uc-doc/administration/voicemails.md
- content/uc-doc/api_sdk/rest_api/confd/user_import.md
- content/uc-doc/api_sdk/rest_api/conventions.md
- content/uc-doc/api_sdk/rest_api/quickstart.md
- content/uc-doc/contributors/network.md
- content/uc-doc/system/wazo-auth/introduction.md
- content/uc-doc/upgrade/upgrade_notes.md
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1747
> use confd without ssl by default

- content/uc-doc/upgrade/upgrade_notes.md
This reverts commit daa7aafd3aac86da4ca606eadc6673a823bfec69.
> Revert "doc: upgrade notes: phoned reverse-proxied"

- src/component/home/index.js
Change homepage button, since we changed the text in the header.
> Change homepage button for API Documentation

- content/uc-doc/contributors/network.md
- content/uc-doc/upgrade/upgrade_notes.md
Depends-on: https://github.com/wazo-platform/wazo-platform.org/pull/183
> Pull request for WAZO-1795-calld-without-https

- content/uc-doc/contributors/network.md
- content/uc-doc/upgrade/upgrade_notes.md
Depends-on: https://github.com/wazo-platform/wazo-platform.org/pull/184
> Pull request for WAZO-1796-call-logd-without-https

- content/uc-doc/contributors/network.md
- content/uc-doc/upgrade/upgrade_notes.md
Depends-on: https://github.com/wazo-platform/wazo-platform.org/pull/185
> Pull request for WAZO-1797-webhookd-without-https

- content/uc-doc/upgrade/upgrade_notes.md
Depends-On: https://github.com/wazo-platform/wazo-confgend/pull/29
> upgrade notes: remove chan_sip generator from confgend

- content/sections.yaml
- gatsby-node.js
- src/component/404.js
- src/component/dev/index.js
- src/component/documentation/api.js
- src/component/documentation/console.js
- src/component/documentation/helper.js
- Fix Api References under **Management platform** section
- Fix Api Console under **Management platform** section
- Also add redirection, for indexed page on Google. 
_Note : Overview are hidden, because don't have any content for this section for now._
`FOR_DEVELOPER=1 yarn start`
Jira-Issue: https://wazo-dev.atlassian.net/browse/WP-60
> [WP-60] Fix Management platform bad links on developer.wazo.io

- content/blog/sprint-review-1915.md
- content/blog/sprint-review-1916.md
- content/blog/sprint-review-1917.md
- content/blog/sprint-review-2001.md
- content/blog/sprint-review-2002.md
- content/blog/sprint-review-2003.md
- content/blog/sprint-review-2004.md
- content/blog/sprint-review-2005.md
- content/blog/sprint-review-2006.md
- content/blog/sprint-review-2007.md
- content/blog/sprint-review-2008.md
- content/blog/sprint-review-2009.md
- content/contribute.md
- content/contribute/code.md
blog: add sprint-review 20.09
add link for upgrade notes 20.09
> Pull request for sprint-review-2009

- content/uc-doc/system/wazo-auth/introduction.md
- content/websocketd/app.md
Why:
* xivo_user is deprecated
> rename xivo_user to wazo_user

- content/sections.yaml
- gatsby-node.js
- package.json
- src/component/documentation/graphql.js
- src/component/documentation/index.js
- yarn.lock
I was testing Seb's excellent work on the backend, figured i'd take a little time to embed GraphiQL. Accessible at `/documentation/graphql/contact`. Needless to say, it's a work in progress. 
Jira-Issue: https://wazo-dev.atlassian.net/browse/WP-61
> [WP-61] GraphiQL Integration

- content/uc-doc/system/wazo-auth/introduction.md
- content/uc-doc/system/wazo-dird/configuration.md
- content/uc-doc/system/wazo-dird/introduction.md
reason: this option has been removed
> remove invalid foreground option

- content/uc-doc/administration/call_recording/index.md
- content/uc-doc/administration/fax/index.md
- content/uc-doc/administration/hardware/introduction.md
- content/uc-doc/administration/hardware/load_modules.md
- content/uc-doc/administration/interconnections/xivo_with_pbx.md
- content/uc-doc/api_sdk/rest_api/acl.md
- content/uc-doc/community/index.md
- content/uc-doc/contributors/contributing_doc.md
- content/uc-doc/contributors/generate_custom_prompts.md
- content/uc-doc/high_availability/berofos.md
- content/uc-doc/high_availability/introduction.md
- content/uc-doc/system/consul.md
- content/uc-doc/system/wazo-auth/introduction.md
- content/uc-doc/troubleshooting/index.md
- content/uc-doc/upgrade/upgrade_notes.md
- content/uc-doc/upgrade/upgrade_notes_details/16-16/xivo_to_wazo.md
- content/uc-doc/upgrade/upgrade_notes_details/19-03/sounds.md
- content/uc-doc/upgrade/upgrade_notes_details/19-13/buster.md
- content/uc-doc/upgrade/upgrade_specific_version/archives-from-wazo-buster.md
- content/uc-doc/upgrade/upgrade_specific_version/archives-from-wazo-jessie.md
- content/uc-doc/upgrade/upgrade_specific_version/archives-from-wazo-stretch.md
- content/uc-doc/upgrade/upgrade_specific_version/archives-from-xivo.md
Hint: you should review commit by commit, not the whole diff
> Pull request for troubleshooting-style

- content/uc-doc/contributors/debug_asterisk.md
the old table was not in markdown format and it became unwieldy with all the
columns
> asterisk debug: remove the old table and add text

- content/uc-doc/administration/cli_tools/index.md
- content/uc-doc/troubleshooting/index.md
Why:
* the doc was a bit ambiguous
> Pull request for wazo-debug-cli

- content/blog/introducing-wazotester.md
- content/uc-doc/administration/call_recording/index.md
- content/uc-doc/administration/users/users.md
- content/uc-doc/api_sdk/message_bus.md
- content/uc-doc/api_sdk/rest_api/confd/func_keys.md
- content/uc-doc/contributors/provisioning/managing_plugins.md
- content/uc-doc/system/wazo-auth/stock_plugins.md
- content/uc-doc/system/wazo-dird/configuration.md
Why:
* JSON needs true/false
* YAML prefers true/false
> fix boolean case

- gatsby-node.js
Fix bad links in Algolia search, causing by link starting with a `/`.
> [WAZO-2183] Fix search bad link

- content/uc-doc/system/proxy.md
Why:
* Seems to be more common
> proxy: use scheme in proxy variables

- src/builder/utils.js
- src/component/provisioning/phone.js
- src/component/provisioning/provisioning.scss
> WAZO-2259 Install and limitations integration

- content/confd/description.md
- content/confd/diagram.puml
- content/uc-doc/api_sdk/rest_api/sysconfd/index.md
- content/uc-doc/contributors/network.md
- content/uc-doc/system/index.md
- content/uc-doc/system/log_files.md
- content/uc-doc/system/xivo-sysconfd.md
- content/uc-doc/upgrade/upgrade_notes.md
Relates-To: https://github.com/wazo-platform/xivo-sysconfd/pull/24
> WAZO-1552: rename sysconfd

- zuul.d/run.yaml
> Dry run while testing

- zuul.yaml
> Pass down the secret

- src/component/provisioning/phone.js
- src/component/provisioning/vendor.js
> Fix URL to Supported Devices

- src/component/LayoutPlatform.js
Why:
* Mattermost supersedes IRC
> remove IRC link

- content/uc-doc/upgrade/upgrade_notes.md
> Pull request for upgrade-note-21-07

- tests/src/404.js
> Pull request for fix-links-whitelist

- content/blog/sprint-review-2108.md
- content/uc-doc/upgrade/upgrade_notes.md
> Pull request for 21.08-release

- content/uc-doc/upgrade/upgrade_notes.md
> Pull request for upgrade-note-2109

- content/use-cases.md
- src/component/use-cases/index.js
- src/styles/platform/devaid.scss
- src/styles/platform/pretty-docs.scss
- src/styles/platform/styles.scss
- Normalize font-size, list and title globally (like we did in blog post previously #369)
----
- Improve install page
**Before** 
**After**
> Improve `getting started` page

- content/blog/value-your-cdr-with-machine-learning.md
> Pull request for blog-machine-learning-typos

- zuul.yaml
Test auto-merge while cleaning up the now unrequired job
> Auto merge

- src/styles/corporate/devaid.scss
- src/styles/corporate/pretty-docs.scss
- src/styles/corporate/styles.scss
- src/styles/platform/devaid.scss
- src/styles/platform/pretty-docs.scss
Improve `.header` scoping in css files, was causing an issue inside code highlight.
> Fix `header` class conflicts between header and code hightlight

- content/blog/value-your-cdr-with-machine-learning.md
why: avoid false positive from tests
> use stable url for scikit-learn

- content/uc-doc/api_sdk/rest_api/quickstart.md
- src/component/uc-doc/utils.js
- src/styles/platform/styles.scss
- Remove gap bellow TOC items
- Move REST API - Quickstart first
- Improve content a bit
> UC DOC - REST API Quickstart improvement

- zuul.yaml
Why:
* Try private key with an extra endline
> zuul: update private key

- content/uc-doc/contributors/network.md
- content/uc-doc/upgrade/upgrade_notes.md
> remove unused 5040 from network port

- content/blog/sprint-review-2207.md
Autentication -> Authentication
> Fix type in sprint review 22.07

- src/component/platform/search.js
why: previous refactor/upgrade break this code. All results was hidden
> fix hidden search results

- content/blog/wazo-asterisk-integration.md
- content/dird/description.md
- content/uc-doc/community/index.md
- content/uc-doc/upgrade/upgrade_notes.md
> Pull request for fix-broken-links

- content/uc-doc/system/wazo-auth/stock_plugins.md
> Pull request for auth-ldap

- src/styles/corporate/pretty-docs.scss
- src/styles/platform/documentation.scss
Prevent big schema to break the page
| Before  | After    |
| ----------- | ----------- |
| ![Capture d’écran, le 2022-10-11 à 09 47 29](https://user-images.githubusercontent.com/1503758/195109337-b348ff3d-0c58-4b7a-b45b-b16dd6a4834b.jpg) | ![Capture d’écran, le 2022-10-11 à 09 47 20](https://user-images.githubusercontent.com/1503758/195109366-90fd0ad8-b3d5-4521-ba05-22b138f3d54a.jpg) |
> style: make overview images responsive

- content/provd/admin.md
- content/uc-doc/administration/provisioning/adv_configuration.md
- content/uc-doc/administration/provisioning/basic_configuration.md
- content/uc-doc/administration/provisioning/jitsi.md
- content/uc-doc/contributors/provisioning/developing_plugins.md
- content/uc-doc/contributors/provisioning/httptftp-requests-processing-in-provd-part-1.md
- content/uc-doc/contributors/provisioning/managing_plugins.md
- content/uc-doc/system/backup_restore.md
> Tried to update as many references as possible to match current plugin

- content/uc-doc/installation/install-system.md
why: fresh install from cloud provider (ex: openstack) needs it
> installation: run apt update before install

- content/uc-doc/upgrade/upgrade_notes.md
https://wazo-dev.atlassian.net/browse/WAZO-2854
> Added 23.01 upgrade note on pre-dial handler legacy support removal

- content/uc-doc/upgrade/upgrade_notes.md
Related to: https://github.com/wazo-platform/wazo-auth/pull/270
> upgrade_notes: add wazo-auth username/email case insensitive note

- .prettierrc
- README.md
Otherwise contributors won't know how to make the CI happy.
> Updated README with information on styling

- package.json
- src/component/LayoutCorporate.js
- src/component/documentation/console.js
- yarn.lock
- Make entreprise API works when defining parameters (limit, offset, etc.)
- run `CORPORATE=1 yarn start`
- Open the console for `nestbox-confd`
- Set the `limit=1` on `/customers`
> [WP-883] console fix

- content/uc-doc/contributors/debug_asterisk.md
why: automatically built by debhelper
> use asterisk-dbgsym for asterisk symbol

- content/uc-doc/upgrade/upgrade_notes.md
https://wazo-dev.atlassian.net/browse/WAZO-3361
> Added upgrade notes for WAZO-3267/WAZO-3361

- .pre-commit-config.yaml
Includes two prettier formatters(one specialized for content/uc-doc as in CI).
> Added pre-commit config

- content/webhookd/sequence-diagram.puml
Why:
* Diagram was incomplete and wrong
> webhookd: update sequence diagram

- zuul.d/secrets.md
- zuul.yaml
Why:
Zuul was freshly installed and the encryption keys are different. Secrets need to be updated.
> Update zuul secret with new encryption

- content/uc-doc/contributors/provisioning/developing_plugins.md
Why:
* Following change from xivo-provd-plugins
> provisioning: fix broken link + rename directory

- content/uc-doc/upgrade/upgrade_notes_details/21-01/asterisk_18.md
- content/uc-doc/upgrade/upgrade_notes_details/22-10/asterisk_19.md
- content/uc-doc/upgrade/upgrade_notes_details/23-04/asterisk_20.md
why: old links are not valide anymore
> update asterisk to their new doc website

- content/provd/admin.md
- content/uc-doc/administration/provisioning/adv_configuration.md
- content/uc-doc/upgrade/upgrade_notes_details/22-16/provd_plugins_python3.md
Why:
* without recurse=True, the command does nothing
> Pull request for provisioning-recurse

- content/uc-doc/administration/contact_directories/general.md
- content/uc-doc/administration/contact_directories/index.md
A separate PR will include documentation on the phonebook backend as a separate page.
Eventually each backend may have its own page with details on specific configuration for that backend.
> General documentation for directory configuration

- content/uc-doc/system/https_certificate.md
- content/uc-doc/troubleshooting/index.md
- content/uc-doc/upgrade/upgrade_notes.md
> Pull request for WAZO-1530-rename-wazo-certs

- content/uc-doc/api_sdk/rest_api/confd/func_keys.md
> Pull request for WP-1276-fix-parking-funckeys

- content/uc-doc/installation/install-system.md
As the installation instructions may be followed by any developer, the documentation has been updated to be more understable.
> Update installation documentation

- content/blog/sprint-review-2405.md
> blog 24.05: remove redundant parking feature

- .prettierrc
- src/builder/provisioning.js
- Don't build provisioning page on Corporate version
- Fix provisioning page creation not being await/async
> Stabilize provisioning pages creation

- content/uc-doc/upgrade/upgrade_notes.md
> upgrade notes: deduplicated service logs in 24.11

- content/blog/2022-11-hackathon-coffee-machine.md
- website/blog/2022-11-hackathon-coffee-machine.md
Fix 404 links caused by the old plugins documentation
> Fix 404 links

- website/release-notes/sprint-review-2414.md
- website/release-notes/sprint-review-2415.md
depends-on: https://github.com/TinxHQ/release/pull/104
> fix: bad tag for release note

- Makefile
- package.json
- scripts/beta-sync.sh
- **scripts/beta-sync.sh: use /usr/bin/env bash for runtime environment flexibility**
- **package.json: fix beta-sync command**
- **Makefile: add builder dependency for develop target**
> fix make develop

- .github/workflows/deploy.yml
- .github/workflows/test-deploy.yml
- website/.env.example
- website/.gitignore
- website/docusaurus.config.ts
- website/package.json
- website/yarn.lock
> [WAZO-3819] Add Algolia DocSearch

- tests/Dockerfile
- tests/package.json
- tests/src/404.js
- tests/yarn.lock
Why:
* CI browser is crashing before the end
> tests: update puppeteer and improve 404 checks

- website/blog/wazo-c4-ansible.md
> Pull request for fix-broken-link-ansible

- website/uc-doc/administration/call_recording/index.md
Add the group and queue options
Rewrite the page thanks to AI
> recording: rework the recording page

- website/uc-doc/administration/paging.md
> paging: added info on announcement sound

- src/component/corporate/index.js
Show GraphQL for dird in corporate website.
> fix(corporate): show graphql spec

- Dockerfile
- gatsby-config.js
- package.json
- patches/gatsby-remark-graph+0.2.6.patch
- yarn.lock
- Support mermaid graph inside the old website, until the content is full in the docusaurus version.
> Support mermaid graph inside the old Gatsby

- website/uc-doc/administration/blocklist.md
- website/uc-doc/administration/callerid.md
- website/uc-doc/administration/contact_directories/index.md
- website/uc-doc/administration/index.md
- website/uc-doc/administration/localization.md
- **contact_directories: fix list formatting**
- **callerid/reverse lookup**
- **callerid: anchor alias for internal link**
- **localization: added page**
- **blocklist: new page**
> WAZO 4134 blocklist

- website/uc-doc/administration/index.md
- website/uc-doc/administration/ring_groups.md
- **uc-doc: ring_groups page**
- **uc-doc/administration: added ring groups page to index**
See also: https://github.com/wazo-platform/wazo-confd/pull/534
> ring groups uc doc
