wazo-platform/wazo-platform.org

src/html.js

Just adding **Google Search Console** meta tag to allow single property validation. We already have domain validation, but to link **Google Analytics** with **Google Search** Console we also need to have a single URL property.

Add Google Search Console meta to allow single property validation

---

content/install.md

this has no incidence on the behavior, simply more in line with the API docs

install: fix expiration value type

---

content/install.md

Why:
* By default, Wazo Platform installs development version.
How:
* Explicitly define Debian distribution names

docs: install: how to install stable version

---

content/sections.yaml

Why:
* The URL is only used for the path part, the hostname is ignored. This
removes confusion about which instance is used to serve the OpenAPI
spec.

sections.yaml: remove references to custom instance

---

content/uc-doc/contributors/network.md
content/uc-doc/upgrade/upgrade_notes.md

use plugind without ssl by default

Pull request for WAZO-1814-plugind-without-ssl

---

content/uc-doc/contributors/network.md
content/uc-doc/upgrade/upgrade_notes.md

use setupd without ssl by default
use chatd without ssl by default

Pull request for WAZO-1813-setupd-without-https

---

src/component/documentation/api.js

Hot patch for Redoc and sticky navigation on Google Chrome. Right now we cannot upgrade Redoc easily because of a dependency issue between Gatbsy and Redoc.
See : https://github.com/Redocly/redoc/pull/1185

[WAZO-1823] Fix sticky navigation lost when scrolling on Chrome 80+

---

content/uc-doc/contact_center/agents.md
content/uc-doc/contact_center/index.md
content/uc-doc/contact_center/introduction.md
content/uc-doc/contact_center/queues.md
content/uc-doc/contact_center/reporting.md
content/uc-doc/contact_center/skillbasedrouting.md

- Fix 404 in index page
- Remove useless table of content on top of the pages
- Convert titles to markdown format
- Improve introduction page a bit
- Reformat content for contact center (aka run `yarn format:uc-doc`)

[WAZO-1701] Fix call center 404 and improve pages

---

content/uc-doc/contributors/network.md
content/uc-doc/upgrade/upgrade_notes.md

use provd without ssl by default
fix provd networking info

Pull request for WAZO-1820-provd-without-ssl

---

gatsby-browser.js
gatsby-config.js
package.json
yarn.lock

improve code block readability
use `gatsby-remark-prismjs` to highlight code block
I tried to use `gatsby-remark-highlight-code` without success
The only non-default option is: `noInlineHighlight: true`
If you have other preference, do not hesitate
I tried to use {`numberlines: true}` but our css breaks everything
I did not have updated `packages-lock.json` because I'm still not sure about how to work with this file (should we add only the missing deps or update others deps in the same time, does zuul use it to build site, etc...?) you can add it if you want

highlight markdown block

---

Dockerfile
Makefile
docker-compose.yml
gatsby-node.js

Why:
* Rebuilding the PlantUML files takes a long time
* It is unnecessary if the PlantUML files did not change
How:
* Use `make` to rebuild only if the .svg file is older than the .puml file

rebuild plantuml files only if necessary

---

gatsby-node.js
src/component/documentation/console.js

Why:
* Some module do not have a sibling named "authentication"

fix authentication for some console modules

---

content/uc-doc/administration/call_recording/index.md

reason: original documentation was for *26
ref: https://wazo.readthedocs.io/en/wazo-18.03/administration/call_recording/call_recording.html

call recording: fix wrong information to disable *26

---

content/uc-doc/contact_center/reporting.md

reason: we only support API and don't want to support a documentation
about internal technical details

Pull request for remove-contact-center-reporting-database

---

content/uc-doc/administration/users/csv_import.md

Why:
* They appear in italic due to MD formatting

user import: fix field names

---

zuul.d/pre.yaml
zuul.d/run-copy.yaml
zuul.d/run-search-copy.yaml
zuul.d/run-test.yaml
zuul.d/run.yaml
zuul.yaml

Fix publication

---

content/blog/wazo-auth-refresh-token.md

creating a refresh token does not require an expiration and if it's in the body
the expiration is ignored.

refresh token: remove expiration from example

---

content/uc-doc/installation/install-system.md

curl is not installed in the minimal installation of Debian, but required to follow the guide.

Added curl as Requirement

---

content/uc-doc/api_sdk/rest_api/quickstart.md

why: with acl restriction, is not more possible to use this access

rest api: do not use # access

---

content/uc-doc/administration/import_export.md

sh script needs sudo to be installed. It is not done by default on debian installation.

sudo needs to be installed

---

content/uc-doc/installation/install-system.md

Why:
* The ini language does not display the section names at all, resulting
in an empty line instead of the section name

doc: install: fix missing lines in code blocks

---

content/uc-doc/system/backup_restore.md

Why:
* If not invalidated, wazo-confgend will still use the older cache files

WAZO-2576 backup/restore: remove cache files generated before restore

---

content/uc-doc/upgrade/introduction.md

why: executing command after 22.01 will leave a not-updated key in the
default keyring
only wazo-keyring.gpg is updated

specify version for invalid signature troubleshooting

---

content/uc-doc/upgrade/upgrade_notes.md

Why: title has been modified, anchor link changed as a consequence.

upgrade_notes: fix invalid signature anchor link

---

content/uc-doc/upgrade/upgrade_specific_version/archives-from-wazo-buster.md

why: wazo-dist pelican-buster will set distribution on archive

upgrade: fix wazo-dist command

---

src/component/documentation/overview.js

why: React-Markdown has been migrated from v4 to v8 and renderers
property has been replaced by components. Then this function must be
adapted to the new components concept

fix react-markdown components

---

zuul.yaml

Why:
* The tests are failing on random URLs, making the whole job fail
everyday

zuul: increase ram for periodic job

---

zuul.yaml

why: latest development and dependencies and version need more RAM and
reach 2G to easily
Fix issue during build for https://github.com/wazo-platform/wazo-platform.org/pull/511

increase vm size to have 4GB RAM instead of 2G

---

content/blog/queuemetrics-partnership.md

why: the bot checking for dead link always has a 403 response on this
link. Since we don't really care of this blog post (5 years old). We
don't want to spent time to investigate reason. So removing link seem
good enough solution

remove queuemetric link

---

content/uc-doc/contributors/debug_daemon.md
content/uc-doc/contributors/profile_python.md

https://wazo-dev.atlassian.net/browse/WAZO-2945
Note that this is only relevant to debian-based installation, as it is the python3-twisted debian package that provides the `twistd3` binary to avoid conflict with python 2 installations of twisted(python-twisted in buster and earlier).
The doc will need to be updated if the assumption of a debian installation changes(e.g. for a docker-based wazo stack) or if a future debian version changes this convention(as the python-twisted package is not provided in bullseye, so a conflict is not possible).

WAZO-2945 twistd to twistd3

---

content/contribute/code.md
content/uc-doc/contributors/contributing_to_wazo.md
content/uc-doc/contributors/integration-tests.md

Adapted from document written in context of wazo-confgend and deemed generally useful.
* The new document is placed in [ uc-doc/contributors](/content/uc-doc/contributors) . Would it be better located in [contribute](/content/contribute)?
* As there are already multiple existing sections describing integration tests, there's is a danger of inconsistency and drift. I added a reference to the new document in existing sections. As the new document includes information available in those existing sections, perhaps the content of those sections should be replaced with the link to the new document to avoid redundancy and inconsistency.

Additional Integration tests doc

---

content/uc-doc/upgrade/upgrade_notes.md

Why:
* Easier to find for people having custom events.

upgrade notes: add link to blog post for events

---

src/component/LayoutPlatform.js
src/component/home/index.js
src/styles/platform/devaid.scss
src/styles/platform/styles.scss

Tweaked some improvements for the homepage
- Uniformise link across website (dark + green underline on hover) 
- Install button
- Now redirect to the C5 procedure. (instead of use cases with C4 + C5)
- It's the only yellow button (primary action from the homepage)
- Splitting text inside **What is Wazo Platform**
- Tried to highlight core things in the text
- Created new section **How We Built It**  
- Small footer restructuration

Homepage improvements

---

tests/Dockerfile

Why:
* The current one is based on Debian 9 Stretch, which is too old and
cause certificate verification issues with newer CA certs.

tests: upgrade puppeteer container

---

content/blog/kamailio-consul-service-discovery.md

Pull request for use-new-golang-url

---

tests/src/404.js

Why:
* youtube links are now very likely to fail with automated tools

Pull request for test-flaky-youtube-links

---

content/amid/description.md
content/blog/pjsip-multi-tenant.md
content/uc-doc/administration/interconnections/two_wazo.md
content/uc-doc/administration/interconnections/wazo_with_voip_provider.md
content/uc-doc/administration/nat.md
content/uc-doc/api_sdk/subroutine.md
content/uc-doc/contributors/debug_asterisk.md
content/uc-doc/upgrade/upgrade_notes.md
content/uc-doc/upgrade/upgrade_notes_details/18-12/asterisk_16.md

why: wiki links are redirect to the home page of new docs.asterisk.org

Pull request for fix-asterisk-links

---

Makefile
content/uc-doc/contributors/integration-tests.md

why: it's now the recommended way to use docker compose

use docker compose without hyphen command

---

tests/src/404.js

Why:
* Links are slow to load and reach 30s timeout

tests: exclude gigaset wiki links

---

content/uc-doc/high_availability/introduction.md

Why:
* The master tenant will change on the slave after the first sync
* Services need to update their internal cache for the master tenant
value

ha setup: need to restart services on slave

---

content/uc-doc/contributors/typing.md

Why:
* follow_imports breaks pre-commit typing analysis in some cases

contributors: python typing: remove suggestion for follow_imports

---

content/uc-doc/system/https_certificate.md

why: debianbuster already redirect to snap

update certbot link with os=snap

---

gatsby-config.js
gatsby-node.js
package.json
website/redirects.ts
website/uc-doc/attribution.md
website/uc-doc/index.md
yarn.lock

- Since we upgrade to gatsby v4, redirect were broken. Use adapter to make it work
- Bring back `/uc-doc/attribution` page

Make redirects works

---

Makefile
beta.Dockerfile
docker-compose.beta.yml

Need separate dockerfile, docker-compose file and Makefile targets to develop on the beta website using docker.
- dockerfile with node version and yarn setup for docusaurus website
- docker-compose file with appropriate volume mounts and build parameters
- `make beta/develop` and `make beta/builder` make targets

docker: added alternative docker assets for beta website

---

website/uc-doc/administration/callerid.md
website/uc-doc/administration/incall.md
website/uc-doc/administration/interconnections/wazo_with_voip_provider.md
website/uc-doc/administration/phone_numbers.md

Updates to existing doc and new doc pages and sections for the new caller id feature

[WAZO-3963] selectable caller id

---

gatsby-node.js
src/component/home/index.js
website/redirects.ts
website/uc-doc/administration/index.md

- Typo on `/users/users` redirect
- Fix remaining 404 links

fix: 404 and wrong redirect

---

website/uc-doc/api_sdk/rest_api/troubleshooting.md
website/uc-doc/system/nginx.md
website/uc-doc/upgrade/upgrade_notes.md

Pull request for WAZO-3544-remove-swagger-doc

---

website/release-notes/sprint-review-2505.md

Add a sprint review update for the backported WAZO-4102 reverse lookup change

sprint review 25.05: add reverse lookup change

---

gatsby-node.js

Don't build page for modules/sections that don't have `redocUrl` defined

Don't build api page for SDK libs

---

Jenkinsfile

**why**
It relies on cleanWS, a DSL on Workspace Cleanup plugin. Not an issue as :
- the pipeline runs on an ephemeral runner
- the pipeline is not ran frequently

pipeline: remove post action
